# Generated by Django 5.2.4 on 2025-10-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facility_preference',
            new_name='prefers_facilities',
        ),
        migrations.AddField(
            model_name='profile',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
    ]
